"""Settings constansts."""

# --- Durations ---
POMODORO_MODE_MIN = 25
STANDARD_MODE_MIN = 45
DEFAULT_WORK_DURATION_MIN = STANDARD_MODE_MIN
AVAILABLE_WORK_MODES = [POMODORO_MODE_MIN, STANDARD_MODE_MIN]
BREAK_DURATION_MIN = 5
TIMER_INTERVAL_MS = 1000

# --- Hotkeys ---
MOVE_TIMER_HOTKEY = "ctrl+alt+t"

# --- UI Options ---
MAX_FOCUS_LENGTH = 50
RED_SECOND_THRESHOLD = 60


# --- Screen Dimensions ---
PRELOAD_WIDTH_DEFAULT = 1920
PRELOAD_HEIGHT_DEFAULT = 1080

# --- Load Image Timeout ---
LOAD_IMAGE_TIMEOUT_DEFAULT = 10
